apiVersion: v1
kind: Service
metadata:
  name:  voting-app-service
  labels:
    name : voting-app-service
    app: demo-voting-app

spec:
  type: NodePort
  ports:
  - port:  80
    nodePort:  31056
  selector:
    name: voting-app-pod
    app: demo-voting-app